steps:
  - id: "(1) Executando testes"
    name: "gcr.io/cloud-builders/go"
    args: ["test", "-v", "soma"]
    env: ["GO_PATH=/src"]

  - id: "(2) Construindo app"
    name: "gcr.io/cloud-builders/go"
    args: ["build", "./src/main.go"]

  - id: "(3) Criando container"
    name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/go_ci_test:latest"
      - "."

images:
  - "gcr.io/$PROJECT_ID/go_ci_test:latest"
